CREATE TABLE `board` (
  `seq` INT(11) NOT NULL AUTO_INCREMENT COMMENT '번호',
  `title` VARCHAR(50) NOT NULL COMMENT '제목',
  `content` VARCHAR(200) NULL DEFAULT NULL COMMENT '내용',
  `type` VARCHAR(50) NOT NULL COMMENT '타입',
  `created_at` DATETIME NULL DEFAULT NULL COMMENT '생성일',
  `updated_at` DATETIME NULL DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`seq`)
);
